[package]
name = "block-utils"
version = "0.4.1"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]
description = "Utilities to work with block devices.  Formatting, getting device info, identifying type of device, etc."

# These URLs point to more information about the repository.
documentation = "https://docs.rs/block-utils"
homepage = "https://github.com/cholcombe973/block-utils"
repository = "https://github.com/cholcombe973/block-utils"
readme = "README.md"
license = "MIT"

[dependencies]
fstab = "~0.3"
libudev = "~0.2"
log = "~0.3"
nom = "~3.2"
regex = "~0.2"
shellscript = "~0.3"
uuid = "~0.5"
